version: '3'

services:
  react-app:
    build:
      context: .
    ports:
      - "3001:3000"
    networks:
      - my-network

  nginx-app:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - my-network

networks:
  my-network:
    driver: bridge