version: '3'

services:
  react-app:
    build:
      context: .
      args:
          - PUBLIC_URL=/subdir/
    ports:
      - "3000:3000"
  web-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
